topology_template:
  inputs:
    ## external network
    external_network_name:
      type: string
      default: public
    ## mgmt network
    management_network:
      type: string
      default: sdl-mgmt
    ## images
    ubuntu1604-image:
      type: string
      default: ubuntu-software-config
    kali-image:
      type: string
      default: kali
    vyos-image:
      type: string
      default: vyos1.1.8-2
    ## default u/p
    ssh_username:
      type: string
      default: sdlmgmt
    ## default flavor
    flavor:
      type: string
      default: ds2G
    ## private keys
    private_key_path:
      type: string
    private_key_name:
      type: string
    openstack_config:
      type: map
      entry_schema: string
    proxy_url:
      type: string
      default: http://192.168.168.1:80
    # config
    # networks/hosts

    # NETWORKs #######

    # EXTNET
    net_extnet_cidr: 
      type: string
      default: 192.168.254.0/24

    # SIMINT1
    net_simint1_cidr: 
      type: string
      default: 27.8.0.0/16

    # Outside
    net_outside_cidr: 
      type: string
      default: 203.0.113.0/24

    # DMZ
    net_dmz_cidr: 
      type: string
      default: 198.51.100.0/24

    # Server
    net_server_cidr: 
      type: string
      default: 192.168.2.0/24

    # NODEs ##########

    # dns #

    dns_dmz_ip:
      type: string
      default: 198.51.100.2

    dns_hostname:
      type: string
      default: dns

    dns_domain:
      type: string
      default: { get_input: domain_name }

    dns_dns:
      type: list
      entry_schema:
        type: string
      default:
        - 127.0.0.1

    # provider #
    
    provider_outside_ip:
      type: string
      default: 203.0.113.1

    provider_extnet_ip:
      type: string
      default: 192.168.254.10

    provider_simint1_ip:
      type: string
      default: 27.8.0.1

    provider_hostname:
      type: string
      default: provider

    provider_domain:
      type: string
      default: nodomain

    provider_dns:
      type: list
      entry_schema:
        type: string
      default:
        - 8.8.8.8

    # firewall #

    firewall_outside_ip:
      type: string
      default: 203.0.113.2

    firewall_dmz_ip:
      type: string
      default: 198.51.100.1

    firewall_server_ip:
      type: string
      default: 192.168.2.1

    firewall_hostname:
      type: string
      default: firewall

    firewall_domain:
      type: string
      default: { get_input: domain_name }

    firewall_dns:
      type: list
      entry_schema:
        type: string
      default:
        - { get_input: dns_dmz_ip }

    # root-ns #

    root-ns_simint1_ip:
      type: string
      default: 27.8.8.8

    root-ns_hostname:
      type: string
      default: root-ns

    root-ns_domain:
      type: string
      default: nodomain

    root-ns_dns:
      type: list
      entry_schema:
        type: string
      default:
        - 127.0.0.1

    # www #

    www_dmz_ip:
      type: string
      default: 198.51.100.5

    www_hostname:
      type: string
      default: www

    www_domain:
      type: string
      default: { get_input: domain_name }

    www_dns:
      type: list
      entry_schema:
        type: string
      default:
        - { get_input: dns_dmz_ip }

    www_cms_login:
      type: string
      default: admin

    www_cms_password:
      type: string
      default: 2diffikult

    www_cms_title:
      type: string
      default: ACME

    www_cms_dbname:
      type: string
      default: CMS

    # db #

    db_server_ip:
      type: string
      default: 192.168.2.2

    db_hostname:
      type: string
      default: db

    db_domain:
      type: string
      default: { get_input: localdomain_name }

    db_dns:
      type: list
      entry_schema:
        type: string
      default:
        - { get_input: dns_dmz_ip }
  
    db_admin_pass:
      type: string
      default: venerus

    # client #

    client_simint1_ip:
      type: string
      default: 27.8.9.10

    client_hostname:
      type: string
      default: client

    client_domain:
      type: string
      default: nodomain

    client_dns:
      type: list
      entry_schema:
        type: string
      default:
        - { get_input: root-ns_simint1_ip }

    client_user_username:
      type: string
      default: eve

    client_user_password:
      type: string
      default: supersecret

    # DOMAINs #########
    domain_name:
      type: string
      default: acme.com

    localdomain_name:
      type: string
      default: acme.local